USE [master]
GO
/****** Object:  Database [NeuralNetwork]    Script Date: 08/14/2009 00:16:46 ******/
CREATE DATABASE [NeuralNetwork] ON  PRIMARY 
( NAME = N'NeuralNetwork', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\NeuralNetwork.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NeuralNetwork_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\NeuralNetwork_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'NeuralNetwork', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NeuralNetwork].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [NeuralNetwork] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NeuralNetwork] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NeuralNetwork] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NeuralNetwork] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NeuralNetwork] SET ARITHABORT OFF 
GO
ALTER DATABASE [NeuralNetwork] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NeuralNetwork] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [NeuralNetwork] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [NeuralNetwork] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NeuralNetwork] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NeuralNetwork] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NeuralNetwork] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NeuralNetwork] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NeuralNetwork] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NeuralNetwork] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NeuralNetwork] SET ENABLE_BROKER 
GO
ALTER DATABASE [NeuralNetwork] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NeuralNetwork] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NeuralNetwork] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NeuralNetwork] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NeuralNetwork] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NeuralNetwork] SET READ_WRITE 
GO
ALTER DATABASE [NeuralNetwork] SET RECOVERY FULL 
GO
ALTER DATABASE [NeuralNetwork] SET MULTI_USER 
GO
ALTER DATABASE [NeuralNetwork] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NeuralNetwork] SET DB_CHAINING OFF 